---
title: "00_DataProcessing"
output: html_document
---

# Setup

This document contains the targets definitions for data processing.

Do data exploration in other documents, then when data processing is
clear, copy it into here.

```{r setup, include = FALSE}
library(targets)
library(tarchetypes)
library(geotargets)
```

# Globals

```{targets globals, tar_globals = TRUE}
library(tarchetypes)
library(geotargets)
options(tidyverse.quiet = TRUE)
tar_option_set(
  packages = c(
    "tarchetypes",
    "tidyverse",
    "terra",
    "tidyterra",
    "geotargets",
    "sf",
    "sfheaders",
    "gdalUtilities"
  )
)
tar_source()
```

# Layers

## State Outlines

```{targets state_outlines}
tar_terra_vect(
  state_outlines,
  map_data("state", region = c(
      "Connecticut", "Massachusetts", "Rhode Island", "New Hampshire", "Vermont"
    )) |>
    sfheaders::sf_polygon(
      obj = _,
      x = "long",
      y = "lat",
      polygon_id = "group"
    ) |>
    sf::`st_crs<-`(sf::st_crs("epsg:4326")) |>
    terra::vect()
)
```

```{targets ma_outline}
tar_terra_vect(
  ma_outline,
  state_outlines |>
    filter(group == 3)
)

```

## Town Outlines

```{targets ma_towns_file}
tar_file(
  ma_towns_file,
  file.path("data/raw/MA_CENSUS2020TOWNS_SHP.zip")
)
```

```{targets ma_towns}
tar_terra_vect(
  ma_towns,
  terra::vect(file.path(
    "/vsizip",
    ma_towns_file,
    "CENSUS2020TOWNS_POLY.shp"
  ))
)
```
## NEON AOP HARV

NEON flies over Harvard Forest, and much more.
The flightbox is our region of interest.

```{targets neon_aop_harv_file}
tar_file(
  neon_aop_harv_file,
  file.path("data/raw/NEON_AOP_flightBoxes_0.zip")
)
```

```{targets neon_aop_harv}
tar_terra_vect(
  neon_aop_harv,
  terra::vect(file.path(
     "/vsizip",
     neon_aop_harv_file,
     "AOP_flightBoxes",
     "AOP_flightboxesAllSites.shp"
  )) |>
    filter(siteID == "HARV") |>
    filter(priority == 1)
)
```

## Basemaps

For zoom levels, see:
https://wiki.openstreetmap.org/wiki/Zoom_levels

0. Whole World
5. Country
10. Metropolitan Area
15. Small Road
20. Mid-Size Building

```{targets basemap}
tar_terra_rast(
  basemap,
  {
    neon_aop_harv_xlim <- c(ext(neon_aop_harv)$xmin - 0.015, ext(neon_aop_harv)$xmax + 0.015)
    neon_aop_harv_ylim <- c(ext(neon_aop_harv)$ymin - 0.015, ext(neon_aop_harv)$ymax + 0.015)
    basemap_area <- terra::ext(
      neon_aop_harv_xlim["xmin"],
      neon_aop_harv_xlim["xmax"],
      neon_aop_harv_ylim["ymin"],
      neon_aop_harv_ylim["ymax"]
    ) |>
      terra::vect(crs = crs("epsg:4326"))
    
    neon_aop_web <- basemap_area |>
      terra::project(crs("epsg:3857")) |> # use webmercator
      st_as_sf()
    
    maptiles::get_tiles(
      neon_aop_web,
      provider = "OpenTopoMap",
      zoom = 11,
      crop = TRUE
    )
  }
)
```

```{targets basemap_detail}
tar_terra_rast(
  basemap_detail,
  {
    detail_area <- terra::ext(-72.20, -72.15, 42.50, 42.55) |>
      terra::vect(crs = crs("epsg:4326"))
    detail_xlim <- c(ext(detail_area)$xmin, ext(detail_area)$xmax)
    detail_ylim <- c(ext(detail_area)$ymin, ext(detail_area)$ymax)
    
    detail_area_web <- detail_area |>
      terra::project(crs("epsg:3857")) |> # use webmercator
      st_as_sf()
  
    maptiles::get_tiles(
      detail_area_web,
      provider = "OpenTopoMap",
      zoom = 13,
      crop =TRUE
    )
  }
)
```

## Rope Plots

```{targets rope_plots_file}
tar_file(
  rope_plots_file,
  file.path("data/raw/Rope Plots Data Entry.xls")
)
```

```{targets rope_plots}
tar_terra_vect(
  rope_plots,
  readxl::read_xls(
    rope_plots_file,
    sheet = "Rope Plot Sites"
  ) |>
    mutate(
      lat = as.numeric(gsub("^N ?([^°]+)°.*$", "\\1", GPS)),
      lon = -as.numeric(gsub("^.*W ?([^°]+)°$", "\\1", GPS))
    ) |>
    terra::vect()
)
```

## NLCD

The NLCD available from the MRLC viewer is much higher resolution than
the NLCD available from EarthExplorer.

* MRLC Viewer: https://www.mrlc.gov/viewer/
* Earth Explorer: https://earthexplorer.usgs.gov

MRLC generates a zipfile with the UUIDs both in the name of the
zipfile and in the names of the files contained therein. The UUID
is the identity of the job used to create the file.

Nik's Downloads:

* bddf54a4-322c-40a1-bf88-b050f871fad8: 2024
* c1a704ee-7eb3-47cc-ba90-39e87f9ee635: 1985 - 2024

```{targets nlcd_uuid}
tar_target(
  nlcd_uuid,
  "c1a704ee-7eb3-47cc-ba90-39e87f9ee635"
)
```

```{targets nlcd_year}
tar_target(
  nlcd_year,
  2024
)
```

```{targets nlcd_file}
tar_file(
  nlcd_file,
  {
    file.path(
      "data/raw",
      paste0("NLCD_", nlcd_uuid, ".zip")
    )
  }
)
```

```{targets nlcd}
tar_terra_rast(
  nlcd,
  {
    terra::rast(
      file.path(
        "/vsizip",
        nlcd_file,
        paste0("Annual_NLCD_LndCov_", nlcd_year, "_CU_C1V1_", nlcd_uuid, ".tiff")
      )
    )
  }
)
```

```{targets nlcd_levels}
tar_target(
  nlcd_levels,
    terra::rast(
      file.path(
        "/vsizip",
        nlcd_file,
        paste0("Annual_NLCD_LndCov_", nlcd_year, "_CU_C1V1_", nlcd_uuid, ".tiff")
      )
    ) |>
    levels()
)
```

```{targets nlcd_coltab}
tar_target(
  nlcd_coltab,
    terra::rast(
      file.path(
        "/vsizip",
        nlcd_file,
        paste0("Annual_NLCD_LndCov_", nlcd_year, "_CU_C1V1_", nlcd_uuid, ".tiff")
      )
    ) |>
    coltab()
)
```

## Wetlands

```{targets ma_wetlands_file}
tar_file(
  ma_wetlands_file,
  file.path("data/raw/wetlandsdep.zip")
)
```

```{targets ma_wetlands}
tar_terra_vect(
  ma_wetlands,
  terra::vect(file.path(
    "/vsizip",
    ma_wetlands_file,
    "wetlandsdep",
    "WETLANDSDEP_POLY.shp"
  ))
)
```


# The Rest Of The Map

In general, we'll be plotting a thing, and we'll want the rest of the
map to be consistent. Here is the rest of the map.

Ref: https://knowyourmeme.com/memes/how-to-draw-an-owl

```{targets the_rest_of_the_map}
tar_target(
  the_rest_of_the_map,
  {
    library(ggspatial)
    
    neon_aop_harv_xlim <- c(ext(neon_aop_harv)$xmin - 0.015, ext(neon_aop_harv)$xmax + 0.015)
    neon_aop_harv_ylim <- c(ext(neon_aop_harv)$ymin - 0.015, ext(neon_aop_harv)$ymax + 0.015)
    
    detail_area <- terra::ext(-72.20, -72.15, 42.50, 42.55) |>
      terra::vect(crs = crs("epsg:4326"))
    detail_xlim <- c(ext(detail_area)$xmin, ext(detail_area)$xmax)
    detail_ylim <- c(ext(detail_area)$ymin, ext(detail_area)$ymax)
    
    harvard_forest <- terra::vect(
      tibble(x=-72.1899, y=42.5319),
      crs=crs("epsg:4326")
    )
    
    list(
      geom_spatvector(
        data = neon_aop_harv,
        aes(
          color = "NEON AOP",
          linetype = "NEON AOP"
        ),
        fill = "transparent"
      ),
      geom_spatvector(
        data = ma_towns,
        aes(
          color = "Town Borders",
          linetype = "Town Borders"
        ),
        fill = "transparent"
      ),
      geom_spatvector(
        data = detail_area,
        aes(
          color = "Detail Area",
          linetype = "Detail Area"
        ),
        fill = "transparent"
      ),
      # This one is a black background for the HF triangle;
      # it does not show in the legend.
      geom_spatvector(
        data = harvard_forest,
        color = "black",
        shape = "triangle",
        size = 2.5
      ),
      geom_spatvector(
        data = harvard_forest,
        aes(
          color = "Harvard Forest",
          linetype = "Harvard Forest"
        ),
        shape = "triangle"
      ),
      geom_spatvector(
        data = rope_plots,
        aes(
          color = "Rope Plot",
          linetype = "Rope Plot"
        )
      ),
      coord_sf(
        crs = crs(neon_aop_harv),
        xlim = neon_aop_harv_xlim,
        ylim = neon_aop_harv_ylim
      ),
      scale_color_manual(
        name = "Legend",
        values = c(
          "Town Borders" = "black",
          "NEON AOP" = "red",
          "Detail Area" = "blue",
          "Harvard Forest" = "gold",
          "Rope Plot" = "black"
        ),
        breaks = c(
          "Town Borders",
          "NEON AOP",
          "Detail Area",
          "Harvard Forest",
          "Rope Plot"
        )
      ),
      scale_linetype_manual(
        name = "Legend",
        values = c(
          "Town Borders" = "dotted",
          "NEON AOP" = "solid",
          "Detail Area" = "dashed",
          "Harvard Forest" = "solid",
          "Rope Plot" = "solid"
        ),
        breaks = c(
          "Town Borders",
          "NEON AOP",
          "Detail Area",
          "Harvard Forest",
          "Rope Plot"
        )
      ),
      theme_bw(),
      theme(axis.text.x = element_text(angle = -30, hjust = 0, vjust = 1)),
      annotation_scale(
        location = "br",
        pad_x = unit(0.65, "cm"),
        pad_y = unit(0.45, "cm")
      ),
      annotation_north_arrow(
        location = "tr",
        width = unit(0.75, "cm"),
        pad_x = unit(0.00, "cm"),
        pad_y = unit(1, "cm"),
        style = north_arrow_minimal
      )
    )
  }
)
```

# Adjacency

## Simplified Landcover Classes

```{targets lc4_classes}
tar_target(
  lc4_classes,
  tribble(
    ~ID, ~category,
    1, "Water",
    2, "Impervious",
    3, "Pervious",
    4, "Forest"
  )
)
```

## NLCD Adjacency

```{targets lc4}
tar_terra_rast(
  lc4,
  {
    nlcd_reclassification <- tribble(
      ~is, ~becomes,
      "Open Water", "Water",
      "Developed, Open Space", "Impervious",
      "Developed, Low Intensity", "Impervious",
      "Developed, Medium Intensity", "Impervious",
      "Developed, High Intensity", "Impervious",
      "Barren Land", "Pervious",
      "Deciduous Forest", "Forest",
      "Evergreen Forest", "Forest",
      "Mixed Forest", "Forest",
      "Shrub/Scrub", "Pervious",
      "Grassland/Herbaceous", "Pervious",
      "Pasture/Hay", "Pervious",
      "Cultivated Crops", "Pervious",
      "Woody Wetlands", "Water",
      "Emergent Herbaceous Wetlands", "Water"
    ) |>
      left_join(nlcd_levels[[1]], by = join_by(is == `NLCD Land Cover Class`)) |>
      left_join(lc4_classes, by = join_by(becomes == category)) |>
      select(is = `Pixel Value`, becomes = `ID`)
    
    nlcd |>
      `levels<-`(nlcd_levels) |>
      terra::classify(nlcd_reclassification) |>
      `levels<-`(lc4_classes)
  }
)
```
## Edges

There are multiple ways to find edges. I'll use distance from forest to
non-forest landcover:

- Within 30m = edge
- From 30m to 100m = transitional
- 100m+ = interior

```{targets edge_classes}
tar_target(
  edge_classes,
  tribble(
    ~ID, ~category,
    1, "Edge",
    2, "Transition",
    3, "Interior"
  )
)

```

```{targets edge_distance}
tar_terra_rast(
  edge_distance,
  {
    lc4 |>
      # target = 4 = Forest
      # exclude = 1 = Water
      terra::distance(target = 4, exclude = 1) |>
      filter(category > 0) |>
      mutate(category = case_when(
        category <= 30  ~ 1,
        category <= 100 ~ 2,
        category  > 100 ~ 3
      )) |>
      terra::mask(lc4)
  }
)
```
